{
  config,
  pkgs,
  lib,
  ...
}: let
  # Script that reads nix_secrets and generates SSH host configs.
  # Runs at activation time (not Nix eval time), so it has full filesystem access.
  genSshConfig = pkgs.writeShellScript "gen-ssh-ecoray" ''
    set -euo pipefail
    SECRETS="$HOME/config/nix_secrets"
    OUT="$HOME/.ssh/config.d/ecoray"

    if [ ! -f "$SECRETS" ]; then
      echo "gen-ssh-ecoray: nix_secrets not found at $SECRETS, skipping" >&2
      exit 0
    fi

    # Source the secrets to get env vars
    set -a
    # shellcheck disable=SC1090
    source "$SECRETS"
    set +a

    mkdir -p "$(dirname "$OUT")"

    echo "# Generated by home-manager from nix_secrets — do not edit manually" > "$OUT"

    # Helper: emit a Host block if env vars are set.
    # Usage: emit <aliases> <user_var> <ip_var> [port_var]
    emit() {
      local aliases="$1" user_var="$2" ip_var="$3" port_var="''${4:-}"
      local user="''${!user_var:-}"
      local ip="''${!ip_var:-}"
      if [ -z "$user" ] || [ -z "$ip" ]; then
        return
      fi
      printf '\nHost %s\n    HostName %s\n    User %s\n' "$aliases" "$ip" "$user" >> "$OUT"
      if [ -n "$port_var" ]; then
        local port="''${!port_var:-}"
        [ -n "$port" ] && echo "    Port $port" >> "$OUT"
      fi
    }

    # Host definitions — env vars (ECORAY_*_USER, ECORAY_*_IP, etc.) are set in ~/config/nix_secrets

    emit "se1 ecoray-vps1"     ECORAY_VPS1_USER     ECORAY_VPS1_IP
    emit "se2 ecoray-vps2"     ECORAY_VPS2_USER     ECORAY_VPS2_IP
    emit "se3 ecoray-vps3"     ECORAY_VPS3_USER     ECORAY_VPS3_IP
    emit "mimer ecoray-mimer"  ECORAY_MIMER_USER    ECORAY_MIMER_IP
    emit "freyr ecoray-freyr"  ECORAY_FREYR_USER    ECORAY_FREYR_IP
    # freyr doesn't have ghostty terminfo (yet) — force xterm-256color
    echo "    SetEnv TERM=xterm-256color" >> "$OUT"
    emit "sem ecoray-mac-mini" ECORAY_MAC_MINI_USER ECORAY_MAC_MINI_IP
    emit "sep ecoray-pi"       ECORAY_PI_USER       ECORAY_PI_IP
    emit "termux"              TERMUX_USER          TERMUX_IP          TERMUX_PORT
    emit "windows"             WINDOWS_USER         WINDOWS_IP

    echo "gen-ssh-ecoray: wrote $(wc -l < "$OUT") lines to $OUT" >&2
  '';
in {
  programs.ssh = {
    enable = true;
    enableDefaultConfig = false;
    includes = ["config.d/ecoray"];
    settings."*" = {
      hashKnownHosts = true;
      identitiesOnly = true;
      strictHostKeyChecking = "accept-new";
    };
  };

  # Generate the included SSH config snippet from nix_secrets at switch time
  home.activation.sshEcorayHosts = lib.hm.dag.entryAfter ["writeBoundary"] ''
    $DRY_RUN_CMD ${genSshConfig}
  '';
}
